### ISSUE TITLE
Error while initializing GreenSens, exception: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by larsEisenblatt** [pijiulaoshi/ha_greensens#1]
benutzerdefinierte

Logger: custom_components.greensens
Source: custom_components/greensens/__init__.py:47 
Integration: greensens (documentation, issues) 
First occurred: 17:13:20 (1 occurrences) 
Last logged: 17:13:20

Error while initializing GreenSens, exception: 'NoneType' object is not subscriptable

greensens:
  username: "xxxxxxx"
  password: "xxxxxxx"
  add_main_sensor: true
  name_language: "DE"

**Comment by pijiulaoshi** [comment]
I am sorry, for some reason I wasn't notified about your issue.

Could you get me the full error message? (The one from the full log, not the one you get in the "clean" logs)

**Comment by pijiulaoshi** [comment]
@larsEisenblatt does the component not run at all, or is this occurring every now and then?

**Comment by pijiulaoshi** [comment]
@larsEisenblatt, since I don't have the issue that you encountered, I cannot reproduce/find a solution for it. If you want it fixed, please provide further details.
